name: maosul
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  firebase_messaging:
  firebase_analytics:
  firebase_core:
  shared_preferences:


  adhara_socket_io: ^1.0.1+1
  uuid: ^3.0.5



  cupertino_icons: ^1.0.1
  google_fonts_arabic: ^1.1.7
  carousel_slider: ^4.0.0
  curved_navigation_bar: ^1.0.1
  page_transition: ^2.0.4
  splashscreen: ^1.3.5
  rflutter_alert: ^2.0.4
  pin_code_text_field: ^1.8.0
  argon_buttons_flutter: ^1.1.0
  sweetalert: ^0.0.1
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  http:
  url_launcher:
  email_validator: ^2.0.1
  typicons_flutter: ^0.5.0
  phone_number: ^0.6.2+4
  country_code_picker: ^2.0.2
  simple_animations: ^1.3.3
  flutter_spinkit: ^5.1.0
  gender_selection: ^1.0.0
  emoji_picker:
  get_it:
  package_info:
  flutter_ringtone_player: ^3.1.0
  socket_io_client: ^1.0.1
  geocoder: ^0.2.1


  path_provider_windows: any
  path_provider:
  location:
  google_maps_flutter:

  provider:
  geolocator:
  google_map_location_picker:
  geocoding:
  flutter_svg: ^0.23.0+1




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - lang/
    - assets/introSlider/illustration.png
    - assets/introSlider/illustration2.png
    - assets/introSlider/illustration3.png
    - assets/images/slider_1.png
    - assets/images/slider_2.png
    - assets/images/slider_3.png
    - assets/images/drawer.png
    - assets/images/bgDark.jpg
    - assets/images/bgLight.jpg
    - assets/images/undraw_select_house_qbag.png
    - assets/images/undraw_forgot_password_gi2d.png
    - assets/images/undraw_Login_re_4vu2.png
    - assets/images/undraw_secure_login_pdn4.png
    - assets/images/restaurant.png
    - assets/images/vegetables.png
    - assets/images/sweets.png
    - assets/images/pharmacy.png
    - assets/images/fruits.png
